language: java
sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux 
      jdk: oraclejdk10
    - os: linux 
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install osxfuse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq pkg-config fuse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo modprobe fuse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod 666 /dev/fuse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chown root:$USER /etc/fuse.conf; fi

before_script:
  - uname -a

script:
  - ./gradlew clean check
