environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - choco install winfsp --version 1.11.22176

build_script:
  # UTF-8 encoding is required for jnr to work correctly
  - set JAVA_OPTS="-Dfile.encoding=UTF-8"
  - gradlew.bat build --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  - C:\Users\appveyor\.gradle
